package com.merryyou.mybatis.domian;

import java.util.Date;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.time
     *
     * @return the value of test.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.time
     *
     * @param time the value for test.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}